### PR TITLE
Implement spport for using pipeTransport with attach

### PR DESCRIPTION
**Pull request by gregg-miskelly**
This commit contains Andrew's changes for pipeTransport attach rebased on master.

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
@WardenGnaw please do a quick review

**Comment by rajkumar42** [comment]
👍

**Comment by munyirik** [comment]
Are there detailed instructions somewhere on how to set this up? I want to attach to a dotnet core app running on an IoT Core device.

**Comment by WardenGnaw** [comment]
@gregg-miskelly has written an example [here](https://github.com/OmniSharp/omnisharp-vscode/wiki/Attaching-to-remote-processes).

**Comment by munyirik** [comment]
I get a strange error in the remote-attach output when I F5...

>Executing: "C:\Users\munyirik\Desktop\putty\plink.exe'" "-pw xxxxx" "administrator@xxxxx" "uname && if [ $(uname) == "Linux" ] ; then ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ $(uname) == "Darwin" ] ; then ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi"

The command works when I run in in a cmd window.

Also I'm doing a self-contained deploy. Do I need to do anything extra to get clrdbg to work?
Thanks!

**Comment by gregg-miskelly** [comment]
@munyirik do you mean Windows IoT Core?

**Comment by munyirik** [comment]
Yes I did

**Comment by gregg-miskelly** [comment]
@munyirik the process listing code that we have is only for Unix. You can explicitly add the process id, and I _think_ that would work.

**Comment by munyirik** [comment]
Doesn't look like I can put the Id explicitly...
>Unable to start debugging. Launch options string provided by the project system is invalid. Name cannot begin with the ''' character, hexadecimal value 0x27. Line 5, position 55.

I'm working on an update to https://marketplace.visualstudio.com/items?itemName=ms-iot.windowsiot. 
The extension allows users to easily copy files to a remote IoT Core device (and run commands e.g. to start a dotnet app). What's missing is a way to attach the debugger.

**Comment by gregg-miskelly** [comment]
@munyirik based on your error message I think you did something wrong. You want something like this (see 'processId').

```json
        {
            "name": ".NET Core IoT Remote Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "1234",
            "pipeTransport": {
                "pipeProgram": "c:\\mytools\\plink.exe",
                "pipeArgs": [ "-i", "c:\\users\\greggm\\ssh-key.ppk", "greggm@1.2.3.4", "-batch", "-t" ],
                "debuggerPath": "c:\\clrdbg\\clrdbg",
                "pipeCwd": "${workspaceRoot}"
            },
            "sourceFileMap": {
                "/home/ExampleAccount/ExampleProject": "${workspaceRoot}"
            }
        }
```

Assuming this works, well enough, I would add --
1. You might want to think more about launch then attach since attach is kind of painful (need to enter the process id every time).
2. If you are interested in improving this, we are happy to take a PR to add a `${command.pickRemoteWindowsProcess}`. You can follow this PR as an example. Shouldn't be too hard.

**Comment by munyirik** [comment]
Thanks I'll try that. Where can I get a copy of clrdbg from that I can copy to my device?

**Comment by gregg-miskelly** [comment]
@munyirik good point. I was thinking you could just use the Windows version, but in thinking about this more, I realized that this isn't going to work - our Windows version isn't designed to run on OneCore Windows. Lets talk more offline.

**Pull request merged**
