### PR TITLE
Map all symbol kinds to vscode.SymbolKinds

### PR DESCRIPTION
**Pull request by craig006**
Fixes this issue:
https://github.com/OmniSharp/omnisharp-vscode/issues/1907

### CODE REVIEW

**Comment by rchande** [comment]
@akshita31 Before we merge this, do you mind pulling the branch and verifying the behavior?

**Comment by TheRealPiotrP** [comment]
@rchande how do we add a test for this behavior?

**Comment by rchande** [comment]
@TheRealPiotrP Well, if we had per-feature unit tests, that would be a good place to add these tests. However, we're doing approximately the same mapping in `completionItemProvider.ts`, so this might be a good time to extract out a common helper and add tests for it in a new file under unitTests\. @craig006 Any interest in doing that work, too?

**Comment by akshita31** [comment]
@rchande  The type "Delegate" is missing here. It is not present in SymbolKind as well. Should we go ahead and add that ?

**Comment by rchande** [comment]
@akshita31 Sure. What icon does it show up with now? Note that there's no VSCode icon for "Delegate" https://code.visualstudio.com/docs/extensionAPI/vscode-api#SymbolKind

**Comment by akshita31** [comment]
symbolkinds

Only 3 icons are being used to represent all the types.

**Comment by akshita31** [comment]
Currently it is defaulting to a class type, hence we are getting a symbol for the class only.

**Comment by akshita31** [comment]
The change does make the functionality a lot better. @craig006 could you add a case for `Delegate` as well with the return type as `SymbolKind.Method` ?

**Comment by DustinCampbell** [comment]
Assuming @craig006 doesn't have the time at the moment, can we take this PR and make the change @akshita31 suggested separately?

**Comment by rchande** [comment]
Thanks for your contribution @craig006! This has been merged.

**Pull request merged**
