### PR TITLE
Fix all providers support

### PR DESCRIPTION
**Pull request by savpek**
Vscode implementation for https://github.com/OmniSharp/omnisharp-roslyn/pull/1581

Todo:
- Tests (once omnisharp-roslyn side is available for CI builds)
- Refactor copy-paste code from service as common base or something.

Supports:
 - Fix one category (by ID) to fix in document, project and solution scope.
 - Fix all autofixable issues in document scope.
 - Fix all issues in current document on save.

Document scope
fix_onebyone_document

Project scope
fix_one_by_one_project

Solution scope:
solution_scope_fix

Fix all issues on document when saved at vscode:

autofix_on_save

### CODE REVIEW

**Comment by JoeRobich** [comment]
Updating OmniSharp to include the server-side changes in https://github.com/OmniSharp/omnisharp-vscode/pull/3960

**Comment by JoeRobich** [comment]
@savpek Is this ready to go in? GitHub checks didn't update. CI is passing https://travis-ci.org/github/OmniSharp/omnisharp-vscode/builds/716733951

**Comment by savpek** [comment]
> @savpek Is this ready to go in? GitHub checks didn't update. CI is passing https://travis-ci.org/github/OmniSharp/omnisharp-vscode/builds/716733951

I think it is. It's quite a while when i wrote this but based on code it should do 🤔

**Comment by JoeRobich** [comment]
The release of 3.1.401 SDK broke our CI. Fixed by specifying to install 3.1.302. Hopefully this run will pass and we'll merge

**Comment by JoeRobich** [comment]
Passing CI - https://travis-ci.org/github/OmniSharp/omnisharp-vscode/builds/717111983

**Pull request merged**
