### PR TITLE
Update docs for v1.1

### PR DESCRIPTION
**Pull request by gregg-miskelly**
Add "What's new" section and update debugger docs with new features.

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
Here are links to read the formatted view:

https://github.com/gregg-miskelly/omnisharp-vscode/tree/UpdateDocs1.1#whats-new-in-c-extension-version-11
https://github.com/gregg-miskelly/omnisharp-vscode/blob/UpdateDocs1.1/debugger.md#environment-variables

**Comment by gregg-miskelly** [comment]
@DustinCampbell @caslan please review

**Comment by caslan** [comment]
LGTM

**Comment by DustinCampbell** [comment]
:+1:

**Pull request merged**
