### PR TITLE
Update Razor to version 6.0.0-alpha.1.20529.17.

### PR DESCRIPTION
**Pull request by NTaylorMullen**
- Includes a fix for the Razor server ready check.

### CODE REVIEW

**Review by TanayParikh — APPROVED** [review]

**Comment by TanayParikh** [comment]
Changelog needs to be updated with the new version: https://github.com/OmniSharp/omnisharp-vscode/blame/master/CHANGELOG.md#L18

Is this still true?
https://github.com/OmniSharp/omnisharp-vscode/blame/master/CHANGELOG.md#L6

**Comment by NTaylorMullen** [comment]
> Changelog needs to be updated with the new version: https://github.com/OmniSharp/omnisharp-vscode/blame/master/CHANGELOG.md#L18
> 
> Is this still true?
> https://github.com/OmniSharp/omnisharp-vscode/blame/master/CHANGELOG.md#L6

Good eye! Will update

**Review by JoeRobich — APPROVED** [review]

**Review by TanayParikh — APPROVED** [review]

**Comment by JoeRobich** [comment]
Rebuilt 1.23.5 available at https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.5

**Comment by NTaylorMullen** [comment]
Thank you Joey!

**Pull request merged**
