### PR TITLE
check if dotnet is on $PATH by executing 'dotnet --info'

### PR DESCRIPTION
**Pull request by chuckries**
Previously we were manually parsing the path environment variable which is
prone to issue when users $PATH variables are malformed. This should be
more robust.

### CODE REVIEW

**Comment by chuckries** [comment]
@caslan @wesrupert @caslan @rajkumar42

**Comment by rajkumar42** [comment]
:shipit:

**Comment by chuckries** [comment]
fix for #555

**Comment by wesrupert** [comment]
:+1:

**Pull request merged**
