### PR TITLE
Add gulp task to package the extension with vsce.

### PR DESCRIPTION
**Pull request by chuckries**

### CODE REVIEW

**Comment by chuckries** [comment]
@DustinCampbell @gregg-miskelly @caslan

**Comment by DustinCampbell** [comment]
:+1:

**Comment by gregg-miskelly** [comment]
:+1:

**Comment by chuckries** [comment]
`gulp package` will now package the app for upload to the gallery. It is possible to upload directly without first creating a local vsix if we want to do that.

**Pull request merged**
