### PR TITLE
Improved generic method and parameters syntax highlighting

### LINKED ISSUE #89: [C#] Syntax highlighting issue
_From @achardes on March 10, 2016 12:55_

Hi,

It seems there is an issue with the syntax highlighting, see the below capture:

screen shot 2016-03-10 at 13 49 49
All the code below this method keep this color.

Perhaps this is a duplicate, in this case, sorry for the noise. 
(I found the same kind of issues but not for C#...)

Vs code version: 0.10.10 (0.10.10)

_Copied from original issue: Microsoft/vscode#3956_

### PR DESCRIPTION
**Pull request by ivanz**
Also fixes #89 

Before:

image

After:

image

### CODE REVIEW

**Comment by DustinCampbell** [comment]
Looks great @ivanz. I'd love to take this PR. Since this is a PR to a Microsoft repo, let me get the machinery set up to take external PRs. I'll get the ball rolling on that today.

**Comment by ivanz** [comment]
I made some more improvements to handle generic parameters in the method signature and also handle arrays of nullable types:

### Before 

image


### After

image

**Comment by DustinCampbell** [comment]
FWIW, I'm still waiting for the CLA machinery to get set up. It's being worked on though. Once it's ready, would you be willing to sign a Microsoft CLA? (assuming you haven't already)

**Comment by ivanz** [comment]
Yes no problem whatsoever. I have signed one before.

**Comment by DustinCampbell** [comment]
Hi @ivanz, sorry for the delay! The CLA automation is finally set up. We're currently locked down on the master branch. I'll go ahead and rebase for you against dev.

**Comment by DustinCampbell** [comment]
OK -- I've rebased against dev and created a new PR - #191. Thanks @ivanz!

**Pull request closed without merging**
