### PR TITLE
Update debugger.md for rc2

### PR DESCRIPTION
**Pull request by gregg-miskelly**
**This PR should be completed once we release the RC2 version of the extension**

This checkin updates debugger.md for RC2.

### CODE REVIEW

**Comment by DustinCampbell** [comment]
Looks like you need to sign a CLA @gregg-miskelly. Possibly because you haven't joined the .NET Foundation organization?

**Comment by gregg-miskelly** [comment]
I actually am in the .NET Foundation, but I don't remember if I signed the CLA yet.

**Comment by DustinCampbell** [comment]
The bot says no :smile:

**Comment by andschwa** [comment]
@gregg-miskelly Is 0.3.7 the RC2 version of the extension?

**Comment by DustinCampbell** [comment]
Nope -- grab the latest from https://github.com/OmniSharp/omnisharp-vscode/releases for the RC2 version.

**Comment by gregg-miskelly** [comment]
See http://aka.ms/vscclrdogfood for complete instructions if you want to try recent builds of the CLI before they ship.

**Comment by andschwa** [comment]
@gregg-miskelly While I can now debug a `netcoreapp1.0` with RC2 bits, I can no longer debug a `netstandardapp1.5` with RC3 bits using 1.0.3-rc2 of this extension; the latter fails with the usual no CoreCLR events raised error.

**Comment by andschwa** [comment]
:smile:

**Pull request merged**
