### PR TITLE
Hardcode osx.10.11-x64 for osx runtime id

### PR DESCRIPTION
**Pull request by chuckries**
This fixes debugger restoration on osx.10.12.

### CODE REVIEW

**Comment by chuckries** [comment]
fix for #492

**Comment by wesrupert** [comment]
:+1:

**Comment by DustinCampbell** [comment]
:+1:

**Comment by caslan** [comment]
would this continue to work with yosemite?

**Comment by chuckries** [comment]
@caslan Yosemite is 10.10 right? I didn't think we supported Yosemite today, nor did .net. Is that incorrect?

**Comment by gregg-miskelly** [comment]
LGTM

**Comment by gregg-miskelly** [comment]
I think .NET doesn't claim to support 10.10, but it actually works (its what I have on my Mac). I suspect it will continue to work even if we use a 10.11 rid. But I can give it a quick try if we want.

**Comment by gregg-miskelly** [comment]
This works correctly on my OSX 10.10 box.

**Comment by chuckries** [comment]
@gregg-miskelly thanks!

**Pull request merged**
