### PR TITLE
Update Razor Test Plan to include Blazor/Legacy Razor and project information.

### PR DESCRIPTION
**Pull request by NTaylorMullen**
- Also updated the `razor.languageServer.trace` verification item to be the new renamed `razor.trace` name.

aspnet/Razor.VSCode#185

@rchande @akshita31 @danroth27 @SteveSandersonMS

### CODE REVIEW

**Comment by NTaylorMullen** [comment]
This was merged right?

**Comment by rchande** [comment]
@NTaylorMullen Actually, no, looks like I lost track of it.

**Comment by NTaylorMullen** [comment]
Uh oh, does that mean the CTI team verified against the non-updated test plan?

**Comment by rchande** [comment]
I'm asking them to take a look at the updated test plan.

**Pull request merged**
