### PR TITLE
Hover consistency with Visual Studio

### LINKED ISSUE #2610: Make hover experience consistent with Visual Studio
In the "HoverProvider" we are showing all the documentation, however, in Visual Studio we only display the "Summary Text" part of the documentation.

This is the image from Visual Studio
vs_hover

This is the image from the vscode C# extension:
vscode_hover

### PR DESCRIPTION
**Pull request by paladique**
Fixes #2610 

I also changed the display order so that it looks similar to VS's behavior:

image

### CODE REVIEW

**Comment by rchande** [comment]
@paladique Thanks for the PR! LGTM
cc @akshita31

**Comment by paladique** [comment]
Looks I need to fix a test too! Working on that now.

**Comment by rchande** [comment]
@paladique Note that you also need to update
```
1) Hover Provider: single csproj at root of workspace
       Hover returns structured documentation with proper newlines:
```

**Comment by akshita31** [comment]
@paladique Thank you for your contribution. Looks good to me :)

**Comment by akshita31** [comment]
@rchande Should we have a changelog entry for this ?

**Pull request merged**
