### PR TITLE
Changed indents in snippets to use `\t` of  so it follows the editor's indent setting

### PR DESCRIPTION
**Pull request by CiberTurtle**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/OmniSharp/omnisharp-vscode?pullRequest=4924) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OmniSharp/omnisharp-vscode?pullRequest=4924) before we can accept your contribution.<br/><br/>:x: CiberTurtle [sign now](https://cla.dotnetfoundation.org/OmniSharp/omnisharp-vscode?pullRequest=4924)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OmniSharp/omnisharp-vscode?pullRequest=4924) it.</sub>

**Comment by JoeRobich** [comment]
@CiberTurtle VS Code has multiple settings around indentation, such as "Editor: Detect Indentation", "Editor: Auto Indent", and "Editor: Insertion Spaces". I would have expected "Editor: Auto Indent" in particular to fix this up for you. If you have the setting enabled and it isn't handling snippet insertion, then we should open a bug against VS Code.

**Comment by CiberTurtle** [comment]
@JoeRobich I do use the settings you mentioned but I also use a "Editor: Tab Size" of 2 which causes vscode to insert 2 tabs in snippets since the snippets have 4 spaces. I don't think this is a problem with vscode because in the docs say that ["Newlines and embedded tabs will be formatted according to the context in which the snippet is inserted."] (https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets)

**Comment by JoeRobich** [comment]
@CiberTurtle Thanks for the explanation. I understand the situation better now.

**Review by JoeRobich — APPROVED** [review]

**Comment by JoeRobich** [comment]
Thanks @CiberTurtle!

**Pull request merged**
