### PR TITLE
Improve parameter type matching regex

### PR DESCRIPTION
**Pull request by seraku24**
Fixes (again) #657 as well as issues brought up in #670.

- Corrects the order of type, template arguments, nullable type specification and array specifications.
- Ensures array specification support all forms (simple arrays, multi-dimensional arrays, arrays of arrays).

### CODE REVIEW

**Comment by seraku24** [comment]
And for comparison, here are the results of the regex on a pathological test case:

_Current behavior_
omnisharp-syntaxhighlighting-currentregex

_Updated behavior_
omnisharp-syntaxhighlighting-updatedregex

**Comment by ivanz** [comment]
@seraku24  You may want to check if it's handling unsafe pointers (string* ,etc) too since you are at it. Relates to those two issues: #101 and https://github.com/Microsoft/vscode/issues/1093

**Comment by ivanz** [comment]
@seraku24  Also one more thing is to handle @ too e.g. `string @class`

**Comment by ivanz** [comment]
@seraku24  Finally might be worth checking wether your regex also fixes the method return value highlighting problem here: #33

**Comment by seraku24** [comment]
Okay, @ivanz.  I have adjusted the regex to support unsafe pointers as well as reserved keyword escaping:

omnisharp-syntaxhighlighting-updatedregexpart2

Regarding return types, it seems that some types are highlighting correctly already but there are others that are not:

omnisharp-syntaxhighlighting-returntypes

That said, we might want to keep the scope of this PR to just addressing the issues with highlighting parameters, which I believe we have done.

**Comment by ivanz** [comment]
Looks good to me, but @DustinCampbell is the one with the review and merge powers and I believe he is based in the US, so it's just about morning there. Congrats on your first GitHub pull request 🎉

**Comment by seraku24** [comment]
Well, compared to other source/version control systems, git and GitHub have probably been the easiest to work with, _especially_ when compared to Product Studio or TFS.  `(:`

Thanks for the help and encouragement.  I am just glad to be able to offer some of my regex experience at the very least.

**Comment by DustinCampbell** [comment]
LGTM

**Pull request merged**
