### PR TITLE
Hide commands on command palette

### PR DESCRIPTION
**Pull request by scabana**
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/3262

Hides 
- csharp.listProcess
- csharp.listRemoteProcess

As they don't provide value from the command palette.

### CODE REVIEW

**Comment by JoeRobich** [comment]
@scabana Sorry for the long wait on this one. Will get it in.

**Comment by scabana** [comment]
@JoeRobich Cool stuff, just trying to help! Need anything else from me?

**Comment by JoeRobich** [comment]
Passing CI - https://travis-ci.org/github/OmniSharp/omnisharp-vscode/builds/719477660

**Comment by JoeRobich** [comment]
@scabana Thanks again!

**Pull request merged**
