### PR TITLE
Enable travis to use the latest omnisharp build

### PR DESCRIPTION
**Pull request by akshita31**
Added settings.json file to the integration tests folder to enable the latest CI build of omnisharp to be consumed by Travis during testing.

### CODE REVIEW

**Comment by rchande** [comment]
@akshita31 Change looks good, but how are you verifying travis is actually downloading something different? Can you share the relevant log snippet from your build after it completes?

**Comment by akshita31** [comment]
Here is the log : https://api.travis-ci.org/v3/job/347408371/log.txt

Pasting relevant screenshots that show the path from which the server is starting. The path contains the version that is being used.
travis
travis1

**Comment by rchande** [comment]
@akshita31 Thanks. Another question: why are we downloading omnisharp twice?

**Comment by akshita31** [comment]
@rchande: The first time the machine is downloading the C# dependencies which includes the debugger as well. The next download is particular to the "latest" download, where it first downloads the file that contains the information about the latest download and then downloads/skips the appropriate version packages.

**Comment by rchande** [comment]
@akshita31 Sounds good, thanks. LGTM.

**Pull request merged**
