### PR TITLE
Add logModuleLoadEvents launch option configuration

### PR DESCRIPTION
**Pull request by wesrupert**
Add flag to disable logging module load events to the console. Since everything (including debuggee output) is logged to the debug output window in normal scenarios, module load events can cause the log to become cluttered fairly quickly. Setting this flag to false in launch.json will remove the module load events from the log.

### CODE REVIEW

**Comment by wesrupert** [comment]
@caslan @gregg-miskelly @chuckries

**Comment by caslan** [comment]
Instead of doing this, should we have a section for controlling output options in general? i.e. Exception messages, step filtering messages, module load / unload messages, thread exit messages, program output

**Comment by chuckries** [comment]
I'd be fine with that, either way this option needs to be in both sections, launch and attach.

**Comment by chuckries** [comment]
:+1:

**Comment by rajkumar42** [comment]
:shipit:

**Comment by gregg-miskelly** [comment]
NOTE: You _might_ want to hold off actually completing this PR until post escrow when you can insert a new OpenDebugAD7 that has your changes. Though if you really would like to complete it now I will not object as it doesn't break anything - it just will not actually work.

**Comment by gregg-miskelly** [comment]
@jacdavis FYI in case you want this in the C++ extension also

**Comment by gregg-miskelly** [comment]
LGTM

**Comment by wesrupert** [comment]
@gregg-miskelly RE: your note. I'll hold on to this PR for now; it looks like there's a few more logging features planned so it makes sense to wait and add them in one go.

**Comment by wesrupert** [comment]
@caslan @gregg-miskelly @chuckries Here's the additional flags.

**Comment by caslan** [comment]
LGTM

**Comment by gregg-miskelly** [comment]
LGTM

**Pull request merged**
