### PR TITLE
Move omnisharp vscode to the new hover implementation

### PR DESCRIPTION
**Pull request by 333fred**
Hover implemention is in PR here: https://github.com/OmniSharp/omnisharp-roslyn/pull/1860.

Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/3652

### CODE REVIEW

**Comment by 333fred** [comment]
Some examples of what this looks like:
image
image
image
image
image
image

**Comment by 333fred** [comment]
This is not going to pass until we bump the omnisharp server version with the new API.

**Comment by JoeRobich** [comment]
Updating OmniSharp to include the server-side changes in https://github.com/OmniSharp/omnisharp-vscode/pull/3960

**Comment by JoeRobich** [comment]
@333fred GH checks haven't been updating. I saw this test failure in the build log - https://travis-ci.org/github/OmniSharp/omnisharp-vscode/builds/716733894

```
  1 failing
  1) Hover Provider: single csproj at root of workspace
       Hover returns structured documentation with proper newlines:
      AssertionError: expected '```csharp\nbool testissue.Compare(int gameObject, string tagName)\n```\n\nChecks if object is tagged with the tag\\.\n\nReturns:\n\n  Returns true if object is tagged with tag\\.' to equal '```csharp\nbool testissue.Compare(int gameObject, string tagName)\n```\n\nChecks if object is tagged with the tag.\n\nReturns:\n\n  Returns true if object is tagged with tag.'
      + expected - actual
       ```csharp
       bool testissue.Compare(int gameObject, string tagName)
       ```
       
      -Checks if object is tagged with the tag\.
      +Checks if object is tagged with the tag.
       
       Returns:
       
      -  Returns true if object is tagged with tag\.
      +  Returns true if object is tagged with tag.
      
      at Context.<anonymous> (test/integrationTests/hoverProvider.integration.test.ts:47:82)
      at Generator.next (<anonymous>)
      at fulfilled (out/test/integrationTests/hoverProvider.integration.test.js:9:58)
      at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by 333fred** [comment]
@JoeRobich should be fixed. The baseline needed to be updated for the additional escaping done on the server.

**Comment by JoeRobich** [comment]
Passing CI - https://travis-ci.org/github/OmniSharp/omnisharp-vscode/builds/716794826

**Comment by JoeRobich** [comment]
Thanks @333fred!

**Comment by vchirikov** [comment]
Hi, thanks for feature, can we have the same highlighting in `parameter-hints-widget` or it is a vs-code issue?

https://github.com/microsoft/vscode/issues/105286

**Comment by filipw** [comment]
This is a VS Code issue - https://github.com/microsoft/vscode/issues/55044

**Pull request merged**
