### PR TITLE
Highlight body of C# 6 expression bodied members properly.

### LINKED ISSUE #638: C# 6.0 string interpolation does not recognize the end of string
_From @RaulOnk on August 4, 2016 21:47_

- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

When doing string interpolation everything greys out. For example            
public void GreetName() => Console.WriteLine($"Hello {this.Name}");
will grey out everything under that method. It does not recognize where the string ended.

_Copied from original issue: Microsoft/vscode#10146_

### PR DESCRIPTION
**Pull request by ivanz**
Fixes #638, #403, #679, #249 

### Before

image

### After

image

### CODE REVIEW

**Comment by DustinCampbell** [comment]
LGTM

**Comment by DustinCampbell** [comment]
I wish we didn't have to copy paste so much though.

**Comment by ivanz** [comment]
@DustinCampbell I wish we had a way to write tests for this this and avoid regressions in the future ;)

**Comment by DustinCampbell** [comment]
yeah, I want to figure that out too.

**Pull request merged**
