### PR TITLE
Update OmniSharp to 1.34.6

### PR DESCRIPTION
**Pull request by JoeRobich**

### CODE REVIEW

**Comment by JoeRobich** [comment]
@brettfo & @filipw

**Comment by brettfo** [comment]
(but I have no idea why the CI is failing)

**Comment by JoeRobich** [comment]
Needed to set `diagnostic.code` to account for removing the diagnostic Id from the quickfix message. see https://github.com/OmniSharp/omnisharp-roslyn/pull/1623

**Comment by filipw** [comment]
> Needed to set `diagnostic.code` to account for removing the Diagnostic.Id from the message. see [OmniSharp/omnisharp-roslyn#1623](https://github.com/OmniSharp/omnisharp-roslyn/pull/1623)

yes I mentioned that in the other PR. there is an open PR https://github.com/OmniSharp/omnisharp-vscode/pull/3311#issuecomment-543154099

**Comment by JoeRobich** [comment]
> yes I mentioned that in the other PR. there is an open PR [#3311 (comment)](https://github.com/OmniSharp/omnisharp-vscode/pull/3311#issuecomment-543154099)

Ah, let me back out my change and let us take your PR.

**Pull request merged**
