### PR TITLE
Update linux distros for OmniSharp

### PR DESCRIPTION
**Pull request by DustinCampbell**
I'm still testing this but wanted to get the PR out for review.

cc @gregg-miskelly, @caslan

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
LGTM

**Comment by gregg-miskelly** [comment]
@DustinCampbell do you want to merge into release instead of master since your stuff can go out as a non-breaking change? Or do you want to wait and go out with us?

**Comment by DustinCampbell** [comment]
Ubuntu 14.04 and 16.04 tested and working.

**Comment by DustinCampbell** [comment]
@gregg-miskelly: We should all go together. There's no reason to have a half-working extension.

**Comment by DustinCampbell** [comment]
Fedora tested and working

**Comment by DustinCampbell** [comment]
Linux Mint tested and working (picks Ubuntu 14 build as expected)

**Comment by DustinCampbell** [comment]
openSUSE tested and working

**Comment by DustinCampbell** [comment]
OK. Based on testing so far, I'll go ahead and merge this so we can get a build to test everything together.

**Pull request merged**
