### PR TITLE
Adding pipeArgs documentation.

### PR DESCRIPTION
**Pull request by rajkumar42**

### CODE REVIEW

**Comment by rajkumar42** [comment]
@gregg-miskelly @DustinCampbell please review

**Comment by gregg-miskelly** [comment]
@rajkumar42 you need to rerun the package.json generation so that this content will get copied.

**Comment by gregg-miskelly** [comment]
The text itself LGTM.

**Comment by DustinCampbell** [comment]
Is this ready to go?

**Comment by gregg-miskelly** [comment]
Yup

**Pull request merged**
