### PR TITLE
Update CoreCLR to rc2-24008

### PR DESCRIPTION
**Pull request by gregg-miskelly**
This updates the packages that the C# extension uses to packages that
use rc2-24008.

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
@chuckries please review
@MattGertz @jaredpar FYI

**Comment by gregg-miskelly** [comment]
I tested this on OSX, and Windows. I am giving it a quick test on Ubuntu now.

**Comment by gregg-miskelly** [comment]
Ubuntu test passed also.

**Comment by chuckries** [comment]
:+1:

**Pull request merged**
