### PR TITLE
Add --configfile to dotnet commands

### PR DESCRIPTION
**Pull request by chuckries**

### CODE REVIEW

**Comment by chuckries** [comment]
@gregg-miskelly @DustinCampbell

**Comment by gregg-miskelly** [comment]
:+1:

**Comment by chuckries** [comment]
Not sure if this is truly necessary but I don't think it can hurt. I think this will prevent us from also pulling in the user default NuGet.config, but we <clear /> the package sources we try to use anyway, so I think it's fine.

**Comment by gregg-miskelly** [comment]
Makes sense to me. I think you should merge.

**Pull request merged**
