### PR TITLE
enableRoslynAnalyzers flag.

### PR DESCRIPTION
**Pull request by savpek**
Requires https://github.com/OmniSharp/omnisharp-roslyn/pull/1076 from omnisharp-roslyn to function.

Adds flag:
```
"omnisharp.enableRoslynAnalyzers": true
```

That can enable feature without modifying `omnisharp.json` when used with vscode.

### CODE REVIEW

**Comment by akshita31** [comment]
Thanks !

**Comment by savpek** [comment]
I will merge this once analyzers are available on omnisharp-roslyn master branch.

**Comment by akshita31** [comment]
@savpek Any updates here ?

**Comment by savpek** [comment]
@akshita31 waiting for review/approval to omnisharp-roslyn side of analyzers from @rchande and @david-driscoll

**Comment by savpek** [comment]
@akshita31 @rchande this probably can be merged since OmniSharp/omnisharp-roslyn#1076 is available in master branch.

**Comment by akshita31** [comment]
It would be better to merge this when we include a new version of omnisharp in the extension.

**Pull request merged**
