### PR TITLE
Initial Razor support

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
This is identical to the earlier PR (#2554) that was merged then reverted, except that in `package.json`, the dependency URLs have been updated to ones we are ready to be used for the initial preview.

### CODE REVIEW

**Comment by NTaylorMullen** [comment]
Now all that's needed is an `omnisharp-roslyn` update 😉

**Comment by rchande** [comment]
@NTaylorMullen https://github.com/OmniSharp/omnisharp-vscode/pull/2573

**Comment by NTaylorMullen** [comment]
Beauutiful!

**Comment by jonathanperis** [comment]
@SteveSandersonMS How we can test it?

**Comment by NTaylorMullen** [comment]
> Great work!!!
> 
> @SteveSandersonMS How we can test it?

@jonathanperis If you install https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.17.0-beta5 release you can then open Razor files in C# projects and get C# completion/IntelliSense. We definitely appreciate the help all help in verifying the Razor functionality!

**Comment by NTaylorMullen** [comment]
> Apparently the C # part does what it should do. Works well. Now we need to check the issue of color highlights, something like works on the full VS, would be perfect. In some scenarios the color combination does not fit very well, especially when using C # outside of the keys, followed only by @. But this is not a matter of language support being tested here.

Ya totally hear you on color highlights, we wish we had time to fix that. That is a known issue that we plan to fix in our next release 😄

**Comment by jonathanperis** [comment]
I will follow this work closely. I'm very interested in this feature.

**Comment by NTaylorMullen** [comment]
@jonathanperis glad to hear! Keep an eye on https://github.com/aspnet/Razor.VSCode. It's closed-source right now so this link is most likely dead; however, we plan to open source it soon!

**Comment by jonathanperis** [comment]
I already added in my favorites to follow when you open source it.

**Comment by NTaylorMullen** [comment]
@jonathanperis it's now open source 😉

**Pull request merged**
