### PR TITLE
Adding support for Oracle Linux.

### PR DESCRIPTION
**Pull request by rajkumar42**
Adding support for Oracle Linux.

### CODE REVIEW

**Comment by rajkumar42** [comment]
@DustinCampbell @gregg-miskelly @caslan

**Comment by gregg-miskelly** [comment]
👍

**Comment by DustinCampbell** [comment]
LGTM (assuming it's tested on Oracle Linux)

**Comment by rajkumar42** [comment]
Tested on Oracle Linux version 7.1

**Comment by DustinCampbell** [comment]
Awesome -- thanks!

**Pull request merged**
