### PR TITLE
Fixes #735 - "Running" forever for folder with multiple .NET Core projects

### LINKED ISSUE #735: "Running" forever for folder with multiple .NET Core projects
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)                                                                                                                        
                                                                                                                                                                       
Product Information:                                                                                                                                                   
 Version:            1.0.0-preview2-003121                                                                                                                             
 Commit SHA-1 hash:  1e9d529bc5                                                                                                                                        
                                                                                                                                                                       
Runtime Environment:                                                                                                                                                   
 OS Name:     ubuntu                                                                                                                                                   
 OS Version:  16.04                                                                                                                                                    
 OS Platform: Linux                                                                                                                                                    
 RID:         ubuntu.16.04-x64
```
VS Code version: 1.4.0
C# Extension version: 1.4.0

I'm working in a folder where there are 3 .NET core projects, one shared library and two `netcoreapp1.0`. There are about 10-15 `.cs` files in each project. No project has warnings or errors.

When I'm editing in VSCode, the right-bottom corner shows the status of OmniSharp. When I choose a project, it works perfect. But when I choose the top level folder, the status shows "Running" forever and the log is:

```
Starting OmniSharp server at 8/30/2016, 5:50:05 PM
    Target: /home/renkun/Workspaces/monotrader

OmniSharp server started
    Path: /home/renkun/.vscode/extensions/ms-vscode.csharp-1.4.0/out/.omnisharp-coreclr/OmniSharp
    PID: 13597

OmniSharp: -s /home/renkun/Workspaces/monotrader --hostPID 10424 DotNet:enablePackageRestore=false --encoding utf-8 --stdio
[INFORMATION:OmniSharp.Startup] Omnisharp server running using Stdio at location '/home/renkun/Workspaces/monotrader' on host 10424.
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /home/renkun/Workspaces/monotrader
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] No solution files found in '/home/renkun/Workspaces/monotrader'
[INFORMATION:OmniSharp.Startup] Configuration finished.
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /projects: 200 44ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /currentfilemembersastree: 200 12ms
```

And it looks like OmniSharp is stuck at `/projects` or `/currentfilemembersastree` forever. No idea what causes this.

But when I create a fresh folder with multiple simple projects, there's no problem at all.

### PR DESCRIPTION
**Pull request by eamodio**

### CODE REVIEW

**Comment by eamodio** [comment]
Damn -- sorry about the trailing whitespace changes :(

**Comment by DustinCampbell** [comment]
We're not actually using typings.json yet (we will in the future). I'd kind of prefer that we either don't use it, or convert *all* of our existing typings to use it.

**Comment by DustinCampbell** [comment]
fixing trailing whitespace is fine. :smile:

**Comment by eamodio** [comment]
@DustinCampbell I'm happy to do either (convert all or nuke it) -- do you have a preference? And if it is to convert everything -- should I do that as a separate PR?

**Comment by eamodio** [comment]
@DustinCampbell Since TypeScript 2 is [moving away from Typings](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) (in favor or npm maybe it is best to leave it alone and I'll just remove the typings stuff. Sound good?

**Comment by DustinCampbell** [comment]
Works for me @eamodio. I'm still digging into TypeScript 2 (excited for tagged unions!) and hadn't dug into the typings changes yet.

**Comment by eamodio** [comment]
@DustinCampbell should be all set now -- remove the typings stuff

**Comment by DustinCampbell** [comment]
LGTM

**Comment by DustinCampbell** [comment]
Note: lodash adds 1.3 MB to node_modules, and around 0.7 MB to the packaged VSIX. 😞

**Comment by eamodio** [comment]
@DustinCampbell :( I could just add the lodash debounce module rather than all of lodash -- that should cut a lot out.

**Comment by DustinCampbell** [comment]
I just noticed it when building the 1.5-beta1. The difference between the 1.4.1 and 1.5-beta1 releases in size is pretty much all lodash. Crazy!

**Comment by DustinCampbell** [comment]
I think it's worth just adding the essential module. The size difference translates to the end user experience because it'll take more time for extension to download and install in VS Code.

**Pull request merged**
