### PR TITLE
Update to latest OmniSharp and prepare for 1.3.0-beta5

### PR DESCRIPTION
**Pull request by DustinCampbell**

### CODE REVIEW

**Comment by DustinCampbell** [comment]
@gregg-miskelly are there any updates to the changelog for the debugger? I did not add anything for the DebugConfiguraitonProvider, but that should probably be called out.

**Comment by gregg-miskelly** [comment]
In addition to the configuration provider, the only other debugger related change to call out is that we fixed the breaking change that VS Code is about to roll out with unit test debugging.

**Comment by gregg-miskelly** [comment]
I will work on updating the changelog for debugger items once you merge this.

**Comment by DustinCampbell** [comment]
Sounds good!

**Pull request merged**
