### PR TITLE
Attempt to fix the extension not finding Mono

### LINKED ISSUE #5454: 1.25.2 no longer finds Mono installation
## Issue Description ##

Though issues #5443 and #5444 were closed with the release of 1.25.2, it appears that Omnisharp still no longer finds the Mono installation. This previous issues seemed to be focused on Mac OS Ventura 13.0 but older versions of Mac OS, for instance Mac OS Monterey 12.6, are still experiencing it.

image

## Steps to Reproduce ##

Upgrade the C# extension from 1.25.0 to 1.25.2. Omnisharp fails and dialog appears when opening a C# project or restarting Onmisharp.

### OmniSharp log ###
<details>OmniSharp failed to start because of missing requirements.</details>

### C# log ###
<details>Empty</details>

## Environment information ##

**VSCode version**: 1.73.1
**C# Extension**: 1.25.2

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.300 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|alphabetical-sorter|ue|2.0.1|
|better-comments|aaron-bond|3.0.2|
|code-spell-checker|streetsidesoftware|2.11.0|
|cold-steel|dev-mdean|0.0.6|
|csharp|ms-dotnettools|1.25.2|
|git-graph|mhutchie|1.30.0|
|luna-paint|Tyriar|0.16.0|
|markdown-all-in-one|yzhang|3.4.3|
|mustache|dawhite|1.1.1|
|vscode-counter|uctakeoff|3.1.0|
|vscode-css-formatter|aeschli|1.0.2|
|vscode-nuget-package-manager|jmrog|1.1.6|;

</details>

### PR DESCRIPTION
**Pull request by ArtyIF**
Should fix #5454

### CODE REVIEW

**Review by filipw — APPROVED** [review]
Thanks this seems good to me.
The older MSBuilds only support single dash args like `-version`. The newer ones (16.10+) support both `--version` and `-version` so of course it makes sense to use the ones that have wider compatibility.

Tagging @333fred @JoeRobich @dibarbet

**Review by dibarbet — APPROVED** [review]
Makes sense to me.  I'll make sure this in the next release.

**Comment by RaulPROP** [comment]
On Ubuntu (22.04 at least), there is also another problem: [the `msbuild` command is a subcommand of `dotnet`](https://github.com/dotnet/sdk/issues/8247#issuecomment-300892165). So to get the version the correct command should be `dotnet msbuild -version -nologo`.

**Comment by 333fred** [comment]
@RaulPROP mono msbuild is not a subcommand of dotnet, which is what this is looking for.

**Comment by ArtyIF** [comment]
> On Ubuntu (22.04 at least), there is also another problem: [the `msbuild` command is a subcommand of `dotnet`](https://github.com/dotnet/sdk/issues/8247#issuecomment-300892165). So to get the version the correct command should be `dotnet msbuild -version -nologo`.

This function is only called with `useModernNet` set to false, i.e. when using Mono instead of .NET 5+ SDK.

**Review by 333fred — APPROVED** [review]

**Pull request merged**
