### PR TITLE
Enable debugging on arm64 devices (testet with rpi4 - 64 bit)

### PR DESCRIPTION
**Pull request by Cyber1000**
See here: 
- https://github.com/OmniSharp/omnisharp-vscode/issues/2771 - This enables debugging on my rpi4 (aarch64), I've also included armv7l (by @kangoroo - see [here](https://github.com/OmniSharp/omnisharp-vscode/issues/2771#issuecomment-590150375)) and arm/arm64
- Didn't need to add new packages, just architectures were missing
- I've tested with:
   - sample blazor weatherforecast
   - dotnetcore 5.0
   - rpi4 (with 64bit rasbian) within a docker-container

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/OmniSharp/omnisharp-vscode?pullRequest=4515) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/OmniSharp/omnisharp-vscode?pullRequest=4515) before we can accept your contribution.<br/><br/>:x: Cyber1000 [sign now](https://cla.dotnetfoundation.org/OmniSharp/omnisharp-vscode?pullRequest=4515)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/OmniSharp/omnisharp-vscode?pullRequest=4515) it.</sub>

**Review by Dean2678 — APPROVED** [review]
Changes look good, will be great to have this functionality!

**Review by Dean2678 — APPROVED** [review]
Changes look good, will be great to have this functionality!

**Comment by davebrunger** [comment]
I built and installed the plugin using your instructions on my Raspberry Pi 4 8GB running Ubuntu 64 bit. Debugging C# works a treat, but is a little slow, but I don't have a great cooling solution. Fantastic job, well done. I hope you get the Pull Request approved.

Now, how do I get the C# code completion to work?...

**Review by sfernandez131 — APPROVED** [review]
I was able to build and run this setup on RaspberryPi 4 armv7l running Raspbian.

**Comment by nvillar** [comment]
This would be a very useful feature; the number of open issues that relate to it suggest that a lot of people would find value in it. What needs to happen to get that final review in place for the pull request to go through?

**Comment by wittelw** [comment]
@Cyber1000, I tried your release from 20 hours ago on **free-armv7l_aarch64** (also didn't work on RPi), but didn't see changes to your armv7l_aarch64 branch, which is for this PR and still doesn't work.

Let me know if you would like me to try and dig into why the **armv7l_aarch64** branch is currently broken (would be nice to have this branch up to date and working with the base branch in case a reviewer with write access takes a look). Thanks!

**Comment by Cyber1000** [comment]
@wittelw free-armv7l_aarch64 is a special branch taken from https://github.com/muhammadsammy/free-omnisharp-vscode which uses the free debugger https://github.com/Samsung/netcoredbg as debugger instead of the original debugger which has another licence.

This may or may not work for you, if you have a different setup. For me free-armv7l_aarch64 works in a gitpod-setup (remote-vscode via browser running on a rpi4 within a docker container - I could test this  some days ago), you should better stay with the armv7l_aarch64-build (this PR).
I didn't have more time, I hope next weekend.

- The only difference that comes into my mind is that I was always using docker on my rpi4, arch won't change, since host und guest are sharing the same kernel, but there may be something different in configuration (for example my current gitpod-install uses ubuntu 20.04 in docker - I can't remember my first approach, but it may be something like debian)
- the automatic build of the packages shouldn't do anything different than the manual usage of vsce. It uses node version 15, if this makes any difference. But you are using latest vscode, so I don't think this matters.

Do you get any error or is there even a problem installing it? Does any of the omnisharp features work (debugging, syntax-highlighting) or nothing?
For example in the omnisharp-log:
image
Thanks!

**Comment by wittelw** [comment]
@Cyber1000 I have been running the extension installed in the Visual Studio Code running directly on my Raspberry Pi 4 / Raspbian. No containers. I also successfully used the working extension for remote debugging running from Visual Studio Code on Windows, both from Windows 10 and from a Windows 11 VM.

There is no problem installing either version of the vsix, just running the debugger with the new version.

My current results:

**Older version csharp-1.23.15.vsix built on August 24th.**

On load this OUTPUT => OmniSharp Log shows the following, but syntax coloring works.

```
Starting OmniSharp server at 11/3/2021, 8:05:47 PM
    Target: /home/pi/src/wwdev/pi/core/StopWatchNet/StopWatchNet.sln

[ERROR] Error: spawn /home/pi/.vscode/extensions/ms-dotnettools.csharp-1.23.15/.omnisharp/1.37.14/run ENOENT
```

Switch to Run and Debug and press F5 and get the following in DEBUG CONSOLE:
```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Loaded '/lib/dotnet/shared/Microsoft.NETCore.App/5.0.9/System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/home/pi/src/wwdev/pi/core/StopWatchNet/bin/Debug/net5.0/StopWatchNet.dll'. Symbols loaded.
...

```

Debugger stops on the set breakpoint and functions as expected (at least simple scenarios I used to debug my code).

**Building current Version csharp-1.23.17.vsix from branch armv7l_aarch64 using node version 16.7.0** (on Windows 11) and installing in Raspberry Pi VS Code gives similar results in the OmniSharp Log.

OUTPUT => OmniSharp Log shows following (syntax coloring also working in this version)

```
Starting OmniSharp server at 11/3/2021, 8:31:31 PM
    Target: /home/pi/src/wwdev/pi/core/StopWatchNet/StopWatchNet.sln

[ERROR] Error: spawn /home/pi/.vscode/extensions/ms-dotnettools.csharp-1.23.17/.omnisharp/1.37.16/run ENOENT
```

Unfortunately no debugging. Switch to Run and Debug and press F5 and there is no output in DEBUG CONSOLE and program doesn't run. No errors are written to the OmniSharp log.

**Comment by Cyber1000** [comment]
Thanks for your investigation!

---
 Seems that I'm getting this too:
`[ERROR] Error: spawn /home/workspace/.openvscode-server/extensions/muhammad-sammy.csharp-1.23.17/.omnisharp/1.37.16/run ENOENT`
But it doesn't have any effect on debugging, **I'll have a look in this too**.

Same here, I didn't notice this in first place, but at least it doesn't seem to be a severe problem:
```
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
```

After installing the vsix I'm getting in C#-console-output (ubuntu because of my docker-setup)
```
Installing C# dependencies...
Platform: linux, aarch64, name=ubuntu, version=20.04

Downloading package '.NET Core Debugger (linux / ARM64)' (55562 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package '.NET Core Debugger (linux / ARM64)'

Finished
```

---
My tests:
- I reactivated my old setup:
  - vscode itself running on windows 10: version 1.62.0
  - docker container is running on rpi4 64bit (connected via docker-context / ssh)
  - vsix installed within docker-container
- primitive testsetup (a simple blazorassembly-project): dotnet new blazorwasm --hosted --pwa

- .vscode/launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/Server/bin/Debug/net5.0/blazor.Server.dll",
            "args": [],
            "cwd": "${workspaceFolder}/Server",
            "stopAtEntry": false
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach"
        }
    ]
}
```
- csharp-1.23.11.vsix (my original-created vsix some months ago) and https://github.com/Cyber1000/omnisharp-vscode/releases/download/v1.23.17-arm64.alpha/csharp-1.23.17.vsix (the new armv7l_aarch64 branch) **both work for me**.

---

Can't say what's exactly different between our setups and why your old vsix worked and the new doesn't. In different setups it helped me to start the program manually with "dotnet watch run" and then attach to the process "blazor.Server"  (for attaching see launch.json above). Maybe this helps, this would only a temporary fix, but at least a step further. Check for differences in the launch.json. The other thing, that comes into my mind: perhaps the output after installing the vsix is different (output of "Installing C# dependencies" -  at the beginning of this comment)

**Comment by Cyber1000** [comment]
Another point: Maybe in this setup the "You may only use the Microsoft .NET Core Debugger (vsdbg) ..." part is relevant and somehow enforced and for whatever reason only a warnign on my system. You may try https://github.com/Cyber1000/omnisharp-vscode/releases/tag/v.1.23.17-free.arm64.alpha, which uses samsung-debugger and not the proprietary vsdbg. You may try it with both "run and debug" and execute "dotnet watch run"  and then attach.

**Comment by Cyber1000** [comment]
I just renamed my releases to reflect, that they are the same as v1.23.17-beta1, you can find them still here (vsix hasn't changed): https://github.com/Cyber1000/omnisharp-vscode/releases

**Comment by wittelw** [comment]
@Cyber1000 I figured out what was preventing debugging on my builds of your current (branch armv7l_aarch64 commit 841ab05847787d3ec6639fa95b49f9b1f2614043). Long story short, my tool chain has apparently changed and now the 'vsce package' command produces .vsix packages containing .debugger, .omnisharp, and .razor subdirectories in the extension folder (as viewed using 7-Zip). If I delete these three folders from the .vsix package, I am able to install, and when I reload and choose Debug in the Activity Bar, I get the 'Installing C# dependencies..." output you noted above. This does NOT show up using the .vsix packages containing the noted subdirectories.

Additional details:
I did a 'git checkout 487f455bcd8d5163c6149c75e4b1c86ada78b5d5' on my branch and compared the contents (kdiff3) of the .vsix package with the older version that has been working, and the only significant differences were the three new subdirectories. Comparing the old working version with a recent build of yours shows additional (expected) differences in extension.js and some other files, but again the main difference is the additional subdirectories. Deleting the three subdirectories allowed this older commit to work again, and as above the same fix works on your current branch.

BTW, the .vsix size of the new builds containing the additional subdirectories is reduced to the same 6.7KB as the old working vsix built using what ever tool chain I had installed back in August.

One other thing I've noticed (both on the August and current builds) is a message in the notification area "Failed to complete the installation of the C# extension. Please see the e...". This could be related to the error in the Omnisharp log we have both noted, but doesn't seem to prevent debugging and disappears on its own.

Here are the tool versions I'm currently using:
```
C:\src\omnisharp-cyber1000>node --version
v16.7.0

C:\src\omnisharp-cyber1000>npm --version
7.20.3

C:\src\omnisharp-cyber1000>vsce --version
2.2.0
```

**Comment by Cyber1000** [comment]
Seems to work natively (tested with dotnet 6.0, vscode 1.64.2, omnisharp 1.24.0)
Closing this PR

**Comment by wittelw** [comment]
I can confirm the debugger works natively on 64-bit Raspberry Pi OS (bullseye) released January 28th, 2022.

Unfortunately, the last version of Omnisharp that will install on the 32-bit version/s of Raspberry Pi OS seems to be [v1.23.16 ](https://github.com/OmniSharp/omnisharp-vscode/releases)from October 05, 2021, and of course this does NOT support debugging. It is what it is...

However I wanted to send a huge thanks out to @Cyber1000  for the work they did on this while waiting for official support.

**Pull request closed without merging**
