### PR TITLE
fs.readFileSync(filename, 'utf8') doesn't strip BOM markers

### PR DESCRIPTION
**Pull request by rajkumar42**
Taking the workaround specified here https://github.com/nodejs/node-v0.x-archive/issues/1918

### CODE REVIEW

**Comment by rajkumar42** [comment]
@gregg-miskelly @chuckries

**Comment by rajkumar42** [comment]
https://github.com/OmniSharp/omnisharp-vscode/issues/577

**Comment by chuckries** [comment]
:+1:

**Comment by caslan** [comment]
LGTM

**Pull request merged**
