### PR TITLE
Add a template tasks.json file

### PR DESCRIPTION
**Pull request by gregg-miskelly**
This checkin adds an example tasks.json that should be added to the user's
project. Eventually this extension will add code to automatically add this
file. This PR adds the file now so that users can easily copy it.

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
@DustinCampbell @chuckries @chrisdias please review.

**Comment by DustinCampbell** [comment]
LGTM

**Comment by chuckries** [comment]
:+1:

**Comment by chrisdias** [comment]
:+1:

**Pull request merged**
