### PR TITLE
Consume omnisharp 1.32.19

### PR DESCRIPTION
**Pull request by rchande**

### CODE REVIEW

**Comment by filipw** [comment]
👍👍👍

**Comment by filipw** [comment]
There is an Azure outage at the moment, which I suspect is the reason for the connectivity failures, see https://azure.microsoft.com/en-us/status/ and https://twitter.com/AzureSupport/status/1124046510411460610

**Comment by rchande** [comment]
Cool, I'll stop flailing for now :)

**Comment by filipw** [comment]
> Cool, I'll stop flailing for now :)

all my work/production services are completely down too 😞

**Comment by filipw** [comment]
I was really hoping that it was the azure outage that broke it but my goodness 😢

**Pull request merged**
