### PR TITLE
Update debugger.md for rc2

### PR DESCRIPTION
**Pull request by gregg-miskelly**
This checkin updates debugger.md to what I believe we will want for RC2 ship.
There are still a few steps in here which aren't correct quite _yet_. My next
checkin will add the work arounds which are needed until we ship.

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
@caslan @Andrew-MSFT @Johnkemnetz please review

**Comment by gregg-miskelly** [comment]
Here is the formatted version of the MD file if you would rather review that --
https://github.com/gregg-miskelly/omnisharp-vscode/blob/UpdateDocs/debugger.md

**Comment by caslan** [comment]
- Not sure if "Debugging code compiled on another computer" section is needed. We already mention enabling portable pdbs in "Windows Only" build step in the section right before it.
- Do we want to refer to running "Debug: Download Debugger" command in the First time setup section?

LGTM

**Comment by gregg-miskelly** [comment]
@caslan, here are my thoughts -

**RE Debugging code compiled on another computer** - personally I think this section is still useful since the first section had a 'Windows only' label, and this text is useful even if you are just consuming a Windows-built library.

**RE Download Debugger** - personally I would rather just have people have this happen automatically. But I am happy to change this if others thinks it improves the experience.

**Comment by chuckries** [comment]
When we set up the aka.ms, does it always point to the dev branch version of this doc? When we merge this into the dev branch won't the master branch then point here, "breaking the instructions" for what we officially have in master? Does this matter at all?

**Comment by gregg-miskelly** [comment]
http://aka.ms/vscclrdebugger points at master.

**Comment by chuckries** [comment]
never mind then.

**Comment by gregg-miskelly** [comment]
Here are my doc plans in full:

1. **Dev**: Get the file to look like at RC2 release (no special instructions for fetching the CLI) -- that is what this PR is trying to do.
2. **Dev**: add in temporary instructions (install C# extension from GitHub, install .NET CLI in new way)
3. **Master**: edit the page to point at dev branch version for folks who want to use newer builds of the CLI
4. **Dev**: take an FI from master, ignore all changes
5. **RC2-Doc**: Take FI from dev branch
6. **RC2-Doc**: Undo the change from step 2.
7. Wait until we are ready to push RC2 to the gallery
8. Merge RC2-Doc->Dev, Merge Dev->Master, extension goes live on gallery

**Comment by johnkemnetz** [comment]
Looks good! A few comments:

- Under "Your Feedback" can we say "File bugs and feature requests **here **[link you already have] and **join our insiders group to help us build great tooling for dot net core** [link to http://landinghub.visualstudio.com/dotnetcoreinsiders]"
- Under "Prerequisites" you list .NET Core RC2, but also have steps for how to install dotnet CLI. I think the wording just needs to be more along the lines of "only works with the RC2 version of dotnet core"
- Prerequisites: Is it any version and SKU of Windows?
- Under "First Time Setup" you may want to clarify that people only need to do step 1 from the Dotnet CLI getting started instructions--the rest are about initializing a new sample project.
- First Time Setup step 3: How do I know what version of the extension I have?
- "Once for each project" step 3: I suggest a small tweak here to clarify what the tasks file is actually doing--eg. "Tasks.json configures Visual Studio Code to run the dotnet CLI build so that your program is automatically up-to-date each time you go to debug it."
- Same place: Can we mention that there are three configurations by default in the launch.json file--one for command line, one for web, and one for attaching to a running process? Each one is included as a template/sample for common debugging scenarios and you can modify these configurations to meet your particular debugging needs.

**Comment by gregg-miskelly** [comment]
@johnkemnetz I made a bunch of changes based on your feedback. I followed what you suggested except for the multiple launch configuration thing - I thought that made more sense as its own step. Let me know what you think.

**Comment by johnkemnetz** [comment]
Looks good. I'm not parsing this sentence though:
Tasks.json configures the command line tool **to run to build** your project.
Maybe:
Tasks.json is used to configure the command line tool to generate a build each time you debug your project.

**Comment by gregg-miskelly** [comment]
Finial set of changes are now on https://github.com/gregg-miskelly/omnisharp-vscode/blob/rc2-debugger-docs/debugger.md

I don't think we want to go through the dev branch though. So I am abandoning this PR.

**Pull request closed without merging**
