### PR TITLE
Pass a semicolon-delimited list of files excluded from VS Code.

### PR DESCRIPTION
**Pull request by rchande**
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/1990

### CODE REVIEW

**Comment by TheRealPiotrP** [comment]
Can we make the list an array instead of a string? This will be easier for users to edit, to diff..

**Comment by TheRealPiotrP** [comment]
Also, a test would be useful :)

**Comment by TheRealPiotrP** [comment]
And are the files consisting of relative paths? Relative to what? What happens if I switch launch targets?

**Comment by rchande** [comment]
@TheRealPiotrP 
> Can we make the list an array instead of a string? This will be easier for users to edit, to diff..
Users define this data by editing artifacts in their repo or in vs code settings. The string generated here will be passed to O# as a command line arg. Arguably, it could be json, but that's not very user-friendly for anyone invoking o# outside of the C# extension.

> And are the files consisting of relative paths? Relative to what? What happens if I switch launch targets?
They're paths relative to the workspace root. Maybe there's some normalizing we need to do if the working directory for o# isn't the workspace root. 

> Also, a test would be useful :)
Ok fine :)

**Comment by firelizzard18** [comment]
Is this still being worked?

**Comment by akshita31** [comment]
cc @rchande

**Comment by rchande** [comment]
@kvalev Thanks for the ping.
@filipw I've implemented your suggestion to use the normal omnisharp configuration mechanism. Any other feedback?

**Comment by WeAthFoLD** [comment]
Is this still being worked on? It would be a very useful feature.

**Comment by rchande** [comment]
Better late than never, this is ready to merge.

**Pull request merged**
