### PR TITLE
Change attach template to use processId by default

### PR DESCRIPTION
**Pull request by caslan**
@gregg-miskelly @DustinCampbell

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
👍

**Comment by DustinCampbell** [comment]
How does setting processId to "0" change the behavior?

**Comment by caslan** [comment]
Debugger will give an error saying you need to configure the process id to attach to (rather than saying "couldn't find process with id ..."

**Comment by DustinCampbell** [comment]
Ah got it. LGTM

**Pull request merged**
