### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by Thaina**
Add jsonValidation with prototyped omnisharp

### CODE REVIEW

**Comment by DustinCampbell** [comment]
@Thaina: Where did this schema come from? Did you create it from scratch? Could you contribute it to https://github.com/OmniSharp/omnisharp-roslyn?

cc @filipw, @david-driscoll?

**Comment by Thaina** [comment]
I use some tool that automatically generate schema from default json. I pick default formatting from some omnisharp repo

**Comment by filipw** [comment]
it's from here https://github.com/SchemaStore/schemastore/pull/260

**Comment by DustinCampbell** [comment]
Shouldn't we add this to the omnisharp-roslyn repo so we can keep it up-to-date?

**Comment by filipw** [comment]
It could even be generated dynamically with JSON.NET based on the object definitions at build time

**Comment by filipw** [comment]
added https://github.com/OmniSharp/omnisharp-roslyn/issues/733

**Comment by DustinCampbell** [comment]
Thanks!

**Comment by DustinCampbell** [comment]
Now that we've got that out of the way... @Thaina, could you use spaces rather than tabs so that your change matches the rest of the file?

**Comment by DustinCampbell** [comment]
Again, please make it looks like the rest of the file. You've indented too far. :smile:

Sorry for being pedantic. :smile:

**Pull request merged**
