### PR TITLE
Merge offline VSIX work to master

### PR DESCRIPTION
**Pull request by gregg-miskelly**
This checkin cherry-pick's commit 8b2cda1ba22c25f465889dff34ac73f34da88965
into master. As part of this, I changed the versions for debugger components
in install.ts to match what the master branch was installing already.

Original description:
    commit 8b2cda1ba22c25f465889dff34ac73f34da88965
    Author: Chuck Ries <Chuck.Ries@microsoft.com>
    Date:   Mon Jun 6 14:41:53 2016 -0700

    Implement task to create offline VSIX's

    This implements a gulp task that creates platform specific vsix's that
    do not require the secondary download/installation steps.

    1. Refactor coreclr-debug/main.ts into activation.ts and install.ts
    2. Remove VS Code specific modules from install.ts so that it can be
    called from gulp
    3. Refactor omnisharpDownload.ts so that it has no VS Code dependencies
    and can be called from gulp task.
    4. Create packaging gulp task that will perform the download of the
    debugger and omnisharp in place, package the extension, and clean it up.
    This repeats for as many platforms as we need to ship.

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
@chuckries please review

**Comment by DustinCampbell** [comment]
:+1: from me

**Comment by rajkumar42** [comment]
👍

**Comment by chuckries** [comment]
:+1:

**Pull request merged**
