### PR TITLE
Creating launch for web or console.

### PR DESCRIPTION
**Pull request by rajkumar42**
It is a web application if it has any dependencies on microsoft.aspnetcore.server.*

### CODE REVIEW

**Comment by rajkumar42** [comment]
@DustinCampbell @gregg-miskelly @chuckries @caslan

**Comment by gregg-miskelly** [comment]
👍

**Comment by chuckries** [comment]
:+1:

**Comment by rajkumar42** [comment]
Merged into dev. 

https://github.com/OmniSharp/omnisharp-vscode/pull/360

**Pull request closed without merging**
