### PR TITLE
Support solution filters (*.slnf)

### PR DESCRIPTION
**Pull request by sharwell**
Addresses https://github.com/dotnet/roslyn/pull/47531#pullrequestreview-485152426

### CODE REVIEW

**Comment by Davilink** [comment]
Any update ?

**Comment by ffMathy** [comment]
Any news?

**Comment by JoeRobich** [comment]
@sharwell Thanks Sam! These changes merged as part of #4481

**Comment by MostHated** [comment]
I am not familiar with solution filter, but came across it when vscode omnisharp was not respecting my folder excludes. Is there an example somewhere of how I might use it to filter out a particular folder?

**Comment by JoeRobich** [comment]
@MostHated Here are the docs https://docs.microsoft.com/en-us/visualstudio/msbuild/solution-filters?view=vs-2019. Solution filters are for filtering out projects that would normally be loaded as part of a Solution file (.sln).

**Pull request closed without merging**
