### PR TITLE
Features to support test adapter extension

### PR DESCRIPTION
**Pull request by Samirat**
I've been working on a C# adapter for [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer). This adds features to OmniSharp to support that.

My adapter: https://github.com/Samirat/omnisharp-test-adapter

In particular this adds:
1. A DiscoverTests request, which lets you get information about all tests in an assembly
2. A NoBuild option for all test requests, which lets you run/debug tests without always building them first
3. An extension export for the TestManager

I've got a separate [PR](https://github.com/OmniSharp/omnisharp-vscode/pull/3573) for the runsettings thing, but it was difficult to extract from this branch, so those changes are included here.

### CODE REVIEW

**Comment by JoeRobich** [comment]
@Samirat Sorry I tried fixing merge conflicts and inadvertently broke the package-lock.json. I can't seem to push changes to the PR branch, but running `npm i` and pushing the changes should resolve this.

**Comment by Samirat** [comment]
@JoeRobich Thanks for the review. I probably need to check this over before merging anyway, make sure I didn't leave it any test code or anything. I'll take a look and get it ready to go tomorrow.

**Comment by JoeRobich** [comment]
@Samirat I believe this (https://github.com/OmniSharp/omnisharp-vscode/pull/3796) will fix the build errors you are seeing. The new TS compiler brought in with `npm i` is more correct about the Package type.

**Comment by JoeRobich** [comment]
@Samirat Thanks!

**Pull request merged**
