### PR TITLE
Update Razor binary dependencies

### PR DESCRIPTION
**Pull request by SteveSandersonMS**
These updates should fix the release blockers identified by @NTaylorMullen.

### CODE REVIEW

**Comment by rchande** [comment]
@SteveSandersonMS @NTaylorMullen The build is failing with
```
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! 
npm ERR! Invalid: lock file's microsoft.aspnetcore.razor.vscode@https://download.visualstudio.microsoft.com/download/pr/273c49f3-fc9b-4140-bc65-b47b9ac61267/84c3319bc81e794e873cb931084cb6c8/microsoft.aspnetcore.razor.vscode-1.0.0-alpha1-20181003.5.tgz does not satisfy microsoft.aspnetcore.razor.vscode@https://download.visualstudio.microsoft.com/download/pr/eee89386-9a82-4b4c-b30a-5857138f2eff/b0583648506c8fffe1ed9ff202702387/microsoft.aspnetcore.razor.vscode-1.0.0-alpha1-20181006.7.tg
```

**Comment by NTaylorMullen** [comment]
@SteveSandersonMS would know better than I as to why. I'm an npm noob 😉

**Comment by NTaylorMullen** [comment]
@SteveSandersonMS ping

**Comment by SteveSandersonMS** [comment]
Rebased on `master` and regenerated `package-lock.json`. Hopefully CI will be OK now!

**Pull request merged**
