### PR TITLE
fix settings type: csharp.unitTestDebugingOptions -> csharp.unitTestDebuggingOptions

### PR DESCRIPTION
**Pull request by zackschuster**

### CODE REVIEW

**Comment by DustinCampbell** [comment]
Hi! Thanks for the contribution to Microsoft C# for Visual Studio Code! If you're able to sign the Contribution License Agreement linked above, we'll can get this merged.

**Comment by DustinCampbell** [comment]
Thanks! This is a breaking change, but I suspect usage is low enough that it'll be OK.

**Comment by zackschuster** [comment]
@DustinCampbell @gregg-miskelly at the very least [there aren't any workspace configs on github](https://github.com/search?l=JSON&q=unitTestDebugingOptions&type=Code&utf8=%E2%9C%93) that use it.

**Comment by gregg-miskelly** [comment]
Thanks for catching this!

**Comment by DustinCampbell** [comment]
@zackschuster: agreed. Thanks again for the contribution!

**Comment by zackschuster** [comment]
of course -- thanks for making such a quality extension! 😄

**Pull request merged**
