### PR TITLE
Merge master into release

### PR DESCRIPTION
**Pull request by DustinCampbell**

### CODE REVIEW

**Comment by DustinCampbell** [comment]
@gregg-miskelly, @chuckries, @caslan, @rajkumar42: I scanned through the changes and it looks right to me. Do any of you want to double-check the debugger changes?

**Comment by gregg-miskelly** [comment]
@DustinCampbell Yeah, we were going to do a quick smoke test of the .vsix. Do you have one built already? (If not, we can build it)

**Comment by DustinCampbell** [comment]
We should build the final from the release branch. Once I merge, could you build it from there?

**Comment by gregg-miskelly** [comment]
That works with me.

**Comment by DustinCampbell** [comment]
look good?

**Comment by gregg-miskelly** [comment]
Yup. Merge it.

**Pull request merged**
