### PR TITLE
Remove dnxcore50 from program path template

### PR DESCRIPTION
**Pull request by chuckries**

### CODE REVIEW

**Comment by chuckries** [comment]
@gregg-miskelly

**Comment by chuckries** [comment]
@caslan

**Comment by chuckries** [comment]
don't merge, Charlie's saying it's not right

**Comment by caslan** [comment]
It needs to be <path-to-program> and not just <My-Project-Name> as they will need to enter names of sub folders.

**Comment by caslan** [comment]
I meant path-to-program and not my-project-name

**Comment by chuckries** [comment]
FYI using brackets in markdown makes your words disappear so that comment is bogus.

**Comment by chuckries** [comment]
how does the diff look now?

**Comment by caslan** [comment]
LGTM

**Comment by gregg-miskelly** [comment]
:+1:

**Pull request merged**
