### PR TITLE
Merge master into release for 1.3 release

### PR DESCRIPTION
**Pull request by chuckries**

### CODE REVIEW

**Comment by chuckries** [comment]
@caslan @gregg-miskelly @wesrupert @DustinCampbell

**Comment by DustinCampbell** [comment]
Let's wait on this merge if that's OK. This release really needs the Dual OmniSharp work.

**Comment by chuckries** [comment]
Abandoning for now. No sense in making this merge until we update clrdbg package references.

**Comment by DustinCampbell** [comment]
I'd like to be more intentional about when we merge to release. Please see the mail I sent about releases late last week. We should at least have a conversation about when the right time is to merge for all parties involved (not just the debugger).

**Comment by chuckries** [comment]
Apologies.

**Pull request closed without merging**
