### PR TITLE
Use omnisharp 1.28.0

### PR DESCRIPTION
**Pull request by rchande**
cc @DustinCampbell @TheRealPiotrP @akshita31

### CODE REVIEW

**Comment by rchande** [comment]
@david-driscoll Want to sign off?

**Comment by DustinCampbell** [comment]
Should there be changelog updates?

**Comment by rchande** [comment]
@DustinCampbell Do you typically update the changelog to reflect o# changes? I'll do that if so.

**Comment by DustinCampbell** [comment]
I update the changelog with any O# changes that are relevant. That is, the changes that affect the C# for VS Code experience. Otherwise, people have to dig to know what's new.

**Pull request merged**
