### PR TITLE
Merge master into release

### PR DESCRIPTION
**Pull request by DustinCampbell**

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
I need to update the debugger packages one more time before we are ready. Builds are inflight now.

**Comment by DustinCampbell** [comment]
Sounds good.

**Comment by DustinCampbell** [comment]
When you update the debugger packages, do you want to just update them in the release branch? I'll be merging release back into master once 1.8 ships.

**Comment by gregg-miskelly** [comment]
Will do

**Pull request merged**
